# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Selenium

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - run: npm install

  selenium:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      #- uses: browser-actions/setup-chrome@v1
      #  with:
       #   chrome-version: 122
      - uses: nanasess/setup-chromedriver@v2
        with:
          # Optional: do not specify to match Chrome's version
          chromedriver-version: '123.0.6312.59'
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'   
      - run: npm install
      - run: npm test
